### ISSUE TITLE
温度調整スライダ

### ISSUE THREAD

**Issue by gaojie429** [kmaehashi/homebridge-nature-remo-cloud-aircon#16]
温度調節スライダの範囲が、暖房、冷房関係なく常に0度から32度になっているのですが、登録しているエアコンの設定可能温度にまで範囲を絞ることは可能でしょうか？
ソースコードを拝見したところ、
getMinTargetTemperature() {
    const v = Math.min(...this._getAllTemperatures());
    return isNaN(v) ? 10.0 : v;
  }
  getMaxTargetTemperature() {
    const v = Math.max(...this._getAllTemperatures());
    return isNaN(v) ? 122.0 : v;
の部分で取得しているようですが(違うかもしれませんが)、うまく動作していないので不具合なのでしょうか？当方、Node.js初心者のため、Pull Requestでの協力はできませんが、すみません・・・

**Comment by kmaehashi** [comment]
HomeKit の仕様上、各モード(暖房/冷房/自動)の温度範囲は共通になっているため、各モードの値域の最大公約数をとる形になっています。

**Comment by gaojie429** [comment]
なるほど、そういうことだったのですね。
了解致しました。
