### ISSUE TITLE
モード「自動」での温度スライダの挙動に関して

### ISSUE THREAD

**Issue by gaojie429** [kmaehashi/homebridge-nature-remo-cloud-aircon#17]
連投失礼致します。
NatureRemo公式アプリでは「自動モード」の時、温度調節スライダーは適温＋ー○○度という表示となっているのですが、このプラグイン経由でのHomeアプリでは「○○度に設定」と表示され、スライダを変更しても「応答なし」と返ってきてしまいます。
修正は可能でしょうか？

**Comment by kmaehashi** [comment]
ご要望ありがとうございます。
エアコンの動作や仕様は機種により異なるため、以下をご提示いただけると助かります。

* HomeBridge のログ
    * 起動時に出力されるエアコンデータ (Discovered aircon: ..., notifying TargetTemperature props: ...)
    * 「応答なし」というエラーが発生した際に出力されるログ
* Nature Remoアプリのエアコン操作画面のスクリーンショット

**Comment by gaojie429** [comment]
お返事、ありがとうございます。
起動時のログはSiriへの命令に関するIssueにコメントしたものと同じです。
応答なしと出た際のログは以下の通りです。(運転モード「自動」で、温度スライダーを22度にした場合)

```
[2019-2-2 22:48:47] [エアコン] making request for update
[2019-2-2 22:48:48] [エアコン] got reponse for update
[2019-2-2 22:48:48] [エアコン] server returned error: {"code":400006,"message":"This air conditioner does not support  mode"}
```
また、Nature Remoの操作画面「自動」モード時のスクリーンショットはこちらです。
![img_4363](https://user-images.githubusercontent.com/36978407/52164949-1debed00-273d-11e9-9105-59bfacbbfa53.PNG)

宜しくお願いします。

追記：
自動モードと暖房、冷房の間で設定温度に隔たりがあるため
運転モードを切り替えた時、それぞれの運転モードで最後に設定した温度をスライダ上で表示する
(例：暖房で25度に、冷房で20度に、自動モードで(適温)+1度に設定した後、運転モードを切り替えてもその運転モードで設定した値を再度温度スライダで表示する)といったことはできますでしょうか？

**Comment by kmaehashi** [comment]
v1.1.0 をリリースしました。再発するようでしたら再度お知らせいただければと思います。
