### ISSUE TITLE
DRY（除湿）モードについて

### ISSUE THREAD

**Issue by takamasa-arch** [kmaehashi/homebridge-nature-remo-cloud-aircon#23]
Nature Remoアプリで対応しているDryモードについては実装できないのでしょうか？CLOUD API上では、dry（除湿）とblow（送風）モードがありそうなので、もし可能なら実装できればと。

[ , cool, warm, dry, blow, auto ]

**Comment by gaojie429** [comment]
残念ながら、Homekitで用意されている運転モードとしては「自動、オフ、冷房、暖房」の4種類の状態のみです。ただし、Nature Remoの方では対応しているので、index.jsの自動運転モードを送信するコマンドに除湿を割り当ててやれば、無理やりですが動かすことが可能です(ホームアプリ上では自動の表示ですが...)
