### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by kmaehashi** [kmaehashi/homebridge-nature-remo-cloud-aircon#3]

**Comment by zcbenz** [comment]
Do you still have plan to publish npm package? It would very helpful when there are multiple plugins installed.

**Comment by kmaehashi** [comment]
@zcbenz Thanks for registering the plug-in on NPM! Could you assign me as a maintainor of the package? (npm username is `kmaehashi`)

**Comment by zcbenz** [comment]
@kmaehashi Glad you are back! I have added you to authors, feel free to remove me once you confirm you get the access.

**Comment by kmaehashi** [comment]
Thank you!
